# This file sets the basic flags for the BYTECODE compiler

set(CMAKE_BYTECODE_COMPILER
	"clang++"
)
set(CMAKE_BYTECODE_SOURCE_FILE_EXTENSIONS cpp;h;hpp)
set(CMAKE_BYTECODE_OUTPUT_EXTENSION .bc)
set(CMAKE_BYTECODE_FLAGS 
	"-DUSE_KLEE -std=gnu++14 -emit-llvm -flto -c -Xclang -disable-O0-optnone"
)
set(CMAKE_BYTECODE_LINK_FLAGS
	#"-fuse-ld=lld"
)
SET(CMAKE_BYTECODE_LINK_EXECUTABLE
	"llvm-link <CMAKE_BYTECODE_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)
SET(CMAKE_BYTECODE_CREATE_STATIC_LIBRARY
	"llvm-link  <CMAKE_BYTECODE_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
)

#if(NOT CMAKE_BYTECODE_COMPILE_OBJECT)
set(CMAKE_BYTECODE_COMPILE_OBJECT "<CMAKE_BYTECODE_COMPILER> <DEFINES> -I <INCLUDES> <FLAGS> <SOURCE> -o <OBJECT>")
#endif()
set(CMAKE_BYTECODE_INFORMATION_LOADED 1)